name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Set up Docker Compose
        run: |
          docker-compose up -d  # Start all containers in the background
          sleep 10  # Wait a few seconds to ensure MongoDB is ready

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down # Stop and remove all containers
